---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cups.fullname" . }}-auth
  labels:
{{- include "cups.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ (default (randAlphaNum 8) .Values.auth.username) | b64enc }}
  password: {{ (default (randAlphaNum 16) .Values.auth.password) | b64enc }}
