---
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cups.fullname" . }}-svc
  labels:
{{- include "cups.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
{{- include "cups.labels" . | nindent 4 }}
  ports:
    - name: web
      protocol: TCP
      port: 631
      targetPort: 631
    - name: airprint
      protocol: UDP
      port: 5353
      targetPort: 5353
    - name: airprint-9
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: {{ .Values.service.type }}
  # externalTrafficPolicy: Local
{{- end }}