apiVersion: v2
name: cups
description: A Helm chart to deploy CUPS (Common UNIX Printing System) as a print server in Kubernetes
type: application
version: 0.1.0
appVersion: "2.4.2"

home: https://www.cups.org/
sources:
  - https://github.com/OpenPrinting/cups
maintainers:
  - name: Daniel Andres
    email: moin@daniel-andres.com
keywords:
  - printing
  - print-server
  - cups
  - ipp
  - infrastructure
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Initial release with basic Deployment, Service, and Secret support
  artifacthub.io/images: |
    - name: cups
      image: docker.io/anujdatar/cups:25.07.01
  artifacthub.io/category: networking
  artifacthub.io/links: |
    - name: Official CUPS documentation
      url: https://www.cups.org/doc/
  artifacthub.io/sensitive: |
    - auth.username
    - auth.password
