name: Publish Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and publish Helm charts
    runs-on: r2dlan-runner

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm charts
        run: |
          mkdir -p .dist
          for dir in charts/*; do
            helm dependency update "$dir" || true
            helm package "$dir" -d .dist
          done

      - name: Create Helm repo index
        run: |
          helm repo index .dist --url https://r2dlan.github.io/helm-charts/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .dist
          destination_dir: .
          keep_files: false
